<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<LangVersion>10.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Product>Jlw.Utilities.Testing</Product>
		<PackageId>Jlw.Utilities.Testing</PackageId>    
		<RepositoryUrl>https://github.com/JasonLWalker/Jlw.Utilities.Testing.git</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>    
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>    
		<PackageReleaseNotes>Library provided as is</PackageReleaseNotes>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<GenerateAssemblyInfo>True</GenerateAssemblyInfo>
		<IsPackable>True</IsPackable>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>$(PackageId)</AssemblyName>
		<RootNamespace>$(PackageId)</RootNamespace>
		<Company>Jason L. Walker</Company>
		<Authors>Jason L. Walker</Authors>
		<Description>Utility library and set of base classes to assist with common scenarios when testing models and data structures via the MSTest unit test framework.</Description>
		<Copyright>Copyright ©2012-2022 Jason L. Walker</Copyright>
		<VersionPrefix Condition="'$(VersionPrefix)' == ''">0.0.0.1</VersionPrefix>
		<Version>$(VersionPrefix)$(VersionSuffix)</Version>
  </PropertyGroup>

	<PropertyGroup>
		<DebugSymbols>true</DebugSymbols>
		<EmbedAllSources>true</EmbedAllSources>
		<DebugType>portable</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<SignAssembly>false</SignAssembly>
		<AssemblyOriginatorKeyFile />
		
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MartinCostello.SqlLocalDb" Version="4.0.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Jlw.Utilities.Data" Version="5.1.9166.6891" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7">
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.7" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="172.76.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

	<ItemGroup>
		<None Include="../README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="DBInstanceFixtures\" />
  </ItemGroup>

</Project>
