param([string]$buildPath)
Import-Module "$PSScriptRoot\templates\ReadmeGenerationUtilities.psm1" -force

Write-Host "===================== Generating Readme Markdown ====================="
$markdown = "<!-- Do not edit this file directly. The README.md file is auto-generated during the build process, and any changes you make will be overwritten. If you need to make changes to this file, update the /build-scripts/templates/ReadmeTemplate.md file.  -->`r`n"
$markdown += Get-Content "$($buildPath)build-scripts\templates\ReadmeTemplate.md" -Raw

$null | sc "$($buildPath)README.md"

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

Set-Content -Path "$($buildPath)README.md" -Value $ExecutionContext.InvokeCommand.ExpandString($markdown)
