using System;

namespace Jlw.Standard.Utilities.Testing.DataSources
{
    public partial class DataSourceValues
    {
        public static readonly object[] ObjectData =
        {
            null,
            0,
            1,
            10,
            100,
            Byte.MinValue,
            Byte.MaxValue,
            char.MinValue,
            char.MaxValue,
            int.MinValue,
            int.MaxValue,
            Int16.MinValue,
            Int16.MaxValue,
            Single.MinValue,
            Single.MaxValue,
            Single.Epsilon,
            Single.NaN,
            Single.NegativeInfinity,
            Single.PositiveInfinity,
            Double.MinValue,
            Double.MaxValue,
            Double.Epsilon,
            Double.NaN,
            Double.NegativeInfinity,
            Double.PositiveInfinity,
            long.MinValue,
            long.MaxValue,
            Decimal.MinValue,
            Decimal.MaxValue,
            Decimal.MinusOne,
            Decimal.One,
            Decimal.Zero,
            "",
            " ",
            " \t\v\r\n",
            "Test123",
            "Test 123",
            "123Test",
            "123 Test",
            "1234.567",
            "12345.678.9",
            "127.0.1.2",
            "2",
            "20",
            "200",
            "https://www.example.org",
            "email@example.com",
            DateTime.MinValue,
            DateTime.MaxValue,
            DateTime.Now,
            DateTime.Today,
            true,
            false,
            "True",
            "False",
            "T",
            "F",
            "t",
            "f",
            "Y",
            "N",
            "y",
            "n",
            "yEs",
            "nO",

        };

    }
}